from enum import IntEnum


class MatchState(IntEnum):
    PRE_MATCH = 0
    START_MATCH = 1
    WARMUP_PERIOD = 2
    AUTO_PERIOD = 3
    PAUSE_PERIOD = 4
    TELEOP_PERIOD = 5
    POST_MATCH = 6
    TIMEOUT_ACTIVE = 7
    POST_TIMEOUT = 8


ARENA_LOOP_PERIOD_MS = 10
ARENA_LOOP_WARNING_US = 3000
DS_PACKET_PERIOD_MS = 500
DS_PACKET_WARNING_MS = 550
PERIODIC_TASK_PERIOD_SEC = 30
MATCH_END_SCORE_DWELL_SEC = 3
POST_TIMEOUT_SEC = 4
PRE_LOAD_NEXT_MATCH_DELAY_SEC = 5
SCHEDULED_BREAK_DELAY_SEC = 5
EARLY_LATE_THRESHOLD_MIN = 2.5
MAX_MATCH_GAP_MIN = 20
